[package]
name         = "watt"
description  = "Modern CPU frequency and power management utility for Linux"
version      = "0.4.0"
edition      = "2024"
authors      = [ "NotAShelf <raf@notashelf.dev>", "RGBCube <git@rgbcu.be>" ]
rust-version = "1.85"

[dependencies]
anyhow              = "1.0"
clap                = { version = "4.0", features = [ "derive", "env" ] }
clap-verbosity-flag = "3.0.2"
ctrlc               = "3.4"
derive_more         = { version = "2.0.1", features = [ "full" ] }
env_logger          = "0.11"
log                 = "0.4"
num_cpus            = "1.16"
serde               = { version = "1.0", features = [ "derive" ] }
thiserror           = "2.0"
toml                = "0.8"
yansi               = { version = "1.0.1", features = [ "detect-env", "detect-tty" ] }
