[workspace]
members  = [ "watt" ]
resolver = "3"

[workspace.package]
authors      = [ "NotAShelf <raf@notashelf.dev>", "RGBCube <git@rgbcu.be>" ]
description  = "Modern CPU frequency and power management utility for Linux"
edition      = "2024"                                                        # Keep in sync with .rustfmt.toml.
license      = "MPL-2.0"
repository   = "https://github.com/notashelf/watt"
rust-version = "1.85"
version      = "0.4.0"

[workspace.dependencies]
anyhow              = "1.0"
clap                = { version = "4.0", features = [ "derive", "env" ] }
clap-verbosity-flag = "3.0.2"
ctrlc               = "3.4"
derive_more         = { version = "2.0.1", features = [ "full" ] }
env_logger          = "0.11"
log                 = "0.4"
num_cpus            = "1.16"
serde               = { version = "1.0", features = [ "derive" ] }
thiserror           = "2.0"
toml                = "0.8"
yansi               = { version = "1.0.1", features = [ "detect-env", "detect-tty" ] }
