# Watt Default Configuration

# Rules are evaluated by priority (higher number => higher priority).
# Each rule can specify conditions and actions for CPU and power management.

# Emergency thermal protection (highest priority).
[[rule]]
cpu.energy-performance-preference = "power"
cpu.frequency-mhz-maximum         = 2000
cpu.governor                      = "powersave"
cpu.turbo                         = false
if                                = { value = "$cpu-temperature", is-more-than = 85.0 }
priority                          = 100

# Critical battery preservation.
[[rule]]
cpu.energy-performance-preference = "power"
cpu.frequency-mhz-maximum         = 800                                                                        # More aggressive below critical threshold.
cpu.governor                      = "powersave"
cpu.turbo                         = false
if.all                            = [ "?discharging", { value = "%power-supply-charge", is-less-than = 0.3 } ]
power.platform-profile            = "low-power"
priority                          = 90

# High performance mode for sustained high load.
[[rule]]
cpu.energy-performance-preference = "performance"
cpu.governor = "performance"
cpu.turbo = true
if.all = [
  { value = "%cpu-usage", is-more-than = 0.8 },
  { value = "$cpu-idle-seconds", is-less-than = 30.0 },
  { value = "$cpu-temperature", is-less-than = 75.0 },
]
priority = 80

# Performance mode when not discharging.
[[rule]]
cpu.energy-performance-bias = "balance_performance"
cpu.energy-performance-preference = "performance"
cpu.governor = "performance"
cpu.turbo = true
if.all = [
  { not = "?discharging" },
  { value = "%cpu-usage", is-more-than = 0.1 },
  { value = "$cpu-temperature", is-less-than = 80.0 },
]
priority = 70

# Moderate performance for medium load.
[[rule]]
cpu.energy-performance-preference = "balance_performance"
cpu.governor = "schedutil"
if.all = [
  { value = "%cpu-usage", is-more-than = 0.4 },
  { value = "%cpu-usage", is-less-than = 0.8 },
]
priority = 60

# Power saving during low activity.
[[rule]]
cpu.energy-performance-preference = "power"
cpu.governor = "powersave"
cpu.turbo = false
if.all = [
  { value = "%cpu-usage", is-less-than = 0.2 },
  { value = "$cpu-idle-seconds", is-more-than = 60.0 },
]
priority = 50

# Extended idle power optimization.
[[rule]]
cpu.energy-performance-preference = "power"
cpu.frequency-mhz-maximum         = 1600
cpu.governor                      = "powersave"
cpu.turbo                         = false
if                                = { value = "$cpu-idle-seconds", is-more-than = 300.0 }
priority                          = 40

# Battery conservation when discharging.
[[rule]]
cpu.energy-performance-preference = "power"
cpu.frequency-mhz-maximum         = 2000
cpu.governor                      = "powersave"
cpu.turbo                         = false
if.all                            = [ "?discharging", { value = "%power-supply-charge", is-less-than = 0.5 } ]
power.platform-profile            = "low-power"
priority                          = 30

# General battery mode.
[[rule]]
cpu.energy-performance-bias       = "balance_power"
cpu.energy-performance-preference = "power"
cpu.frequency-mhz-maximum         = 1800
cpu.frequency-mhz-minimum         = 200
cpu.governor                      = "powersave"
cpu.turbo                         = false
if                                = "?discharging"
priority                          = 20

# Balanced performance for general use. Default fallback rule.
[[rule]]
cpu.energy-performance-preference = "balance_performance"
cpu.governor                      = "schedutil"
priority                          = 0
